// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2q-tj4YVwx1OO1GYF-DkSqb7BV5ljdvc',
    appId: '1:90647274675:web:d10308c729979fcdde7cc6',
    messagingSenderId: '90647274675',
    projectId: 'internship-53f31',
    authDomain: 'internship-53f31.firebaseapp.com',
    storageBucket: 'internship-53f31.appspot.com',
    measurementId: 'G-MPWVL3V8YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9-u7eMAgHJhKWuiHwk-22AH8809SdQF8',
    appId: '1:90647274675:android:d72f2cd34a9f1614de7cc6',
    messagingSenderId: '90647274675',
    projectId: 'internship-53f31',
    storageBucket: 'internship-53f31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6k8DwvU9Ep8h-Ht7r603FDbFHz1FStvE',
    appId: '1:90647274675:ios:e5202bf020d9d5cbde7cc6',
    messagingSenderId: '90647274675',
    projectId: 'internship-53f31',
    storageBucket: 'internship-53f31.appspot.com',
    iosClientId: '90647274675-i5olr0vqgclf35q6dq6j3f13ditpupos.apps.googleusercontent.com',
    iosBundleId: 'com.internship.calculator13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6k8DwvU9Ep8h-Ht7r603FDbFHz1FStvE',
    appId: '1:90647274675:ios:e5202bf020d9d5cbde7cc6',
    messagingSenderId: '90647274675',
    projectId: 'internship-53f31',
    storageBucket: 'internship-53f31.appspot.com',
    iosClientId: '90647274675-i5olr0vqgclf35q6dq6j3f13ditpupos.apps.googleusercontent.com',
    iosBundleId: 'com.internship.calculator13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2q-tj4YVwx1OO1GYF-DkSqb7BV5ljdvc',
    appId: '1:90647274675:web:e8544247ff470c22de7cc6',
    messagingSenderId: '90647274675',
    projectId: 'internship-53f31',
    authDomain: 'internship-53f31.firebaseapp.com',
    storageBucket: 'internship-53f31.appspot.com',
    measurementId: 'G-HYP11LJ840',
  );

}